# Lab 02: Manipulate PyTorch Tensors -- exercise

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [6]:

# write your code here
A = torch.Tensor([[1,2], [3,4]])
B = torch.Tensor([[10,20], [30,40]])
C = A + B
C

tensor([[11., 22.],
        [33., 44.]])

### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [7]:

# write your code here
print(A.dim())
print(A.size())
print(A.type())


2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [8]:

# write your code here
print(A.long())


tensor([[1, 2],
        [3, 4]])


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [11]:

# write your code here
rt = torch.rand(5,2,3)
print(rt)
print(rt.dim())
print(rt.size())
print(rt.size(1))


tensor([[[0.8393, 0.3858, 0.8314],
         [0.8576, 0.8970, 0.5823]],

        [[0.1289, 0.9003, 0.4088],
         [0.2262, 0.3668, 0.2802]],

        [[0.9297, 0.8614, 0.6903],
         [0.0665, 0.7484, 0.0606]],

        [[0.2010, 0.8323, 0.8370],
         [0.7837, 0.3235, 0.9605]],

        [[0.7749, 0.2011, 0.8907],
         [0.1567, 0.8171, 0.7264]]])
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [13]:

# write your code here
zt = torch.zeros(2,3,4,5)
print(zt) # 2 batches of 3 matrices of 4 rows and 5 columns


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
