# Lab 02: Manipulate PyTorch Tensors -- exercise

In [2]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [6]:

# write your code here
A = torch.Tensor([[1,2],[3,4]])
B = torch.Tensor([[10,20],[30,40]])
C = A + B
print(A)
print(B)
print(C)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20.],
        [30., 40.]])
tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [10]:

# write your code here
print(A.dim())
print(A.size())
print(A.type())


2
torch.Size([2, 2])
torch.LongTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [11]:

# write your code here
A = A.long()
print(A.type())


torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [13]:

# write your code here
D = torch.rand(5,2,3)
print(D)
print(D.type())
print(D.dim())
print(D.size())
print(D.size(1))




tensor([[[0.5216, 0.8543, 0.6608],
         [0.6832, 0.0250, 0.1901]],

        [[0.5739, 0.3870, 0.9769],
         [0.7331, 0.6629, 0.3740]],

        [[0.0159, 0.7189, 0.2507],
         [0.2169, 0.4017, 0.2883]],

        [[0.7340, 0.4735, 0.4108],
         [0.8313, 0.7093, 0.9030]],

        [[0.7699, 0.0061, 0.6229],
         [0.9739, 0.7010, 0.2861]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [14]:

# write your code here
E = torch.zeros(2,3,4,5)
print(E)



tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
