
## AI6103 : Deep Learning and Applications
## Xavier Bresson


## Coding Test 1
Date: October 8th, 2020<br>

*Instructions* <br>
Name: Do not forget to add your name to the notebook file "coding_test1_AI6103_YOUR_NAME.ipynb".<br>
Questions: This notebook has 10 questions.<br>
Answers: Write the answers to each question in this notebook.<br>
Type: This test is individual and open-book.<br>
Grading: 1 point for each question.<br>
Output/Timestamp: There is no point if the code has no output (the cell was not executed) or the timestamp is beyond 8:15pm.<br>
Delivery: Upload your notebook to https://drive.google.com/drive/folders/1XkFvpkx17T6lFYakV4CV4JDeBub-t64G by 8:20pm. <br>
Remark: **If certain conditions of the questions (for eg. hyperparameter values) are not stated, you are free to choose anything you want.**<br>


### Question 1

Create a PyTorch tensor $x$ of type FloatTensor, size [2, 5, 7] and filled with value 1. Print the tensor $x$ and its type. Convert the same tensor $x$ to type LongTensor and print its value and type.

In [2]:
%reset -f
import torch
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))

# YOUR CODE HERE
x = torch.ones([2,5,7])
print(x, x.type())
x = x.long()
print(x, x.type())

Timestamp: 20-11-26--17-12-20
tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]]) torch.FloatTensor
tensor([[[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1]]]) torch.LongTensor


### Question 2

Given a color image $x$ represented by a tensor of size (3, 28, 28), with 3 color channels (red, green and blue) and a grid domain of 28 pixels by 28 pixels. 

Transform the image tensor $x$ into a vector of 2,352 elements and print its size.

Transform back the vector to an image tensor of size (3, 28, 28) and print its size.

In [3]:
%reset -f
import torch
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))

x = torch.rand(3,28,28) # given color image

# YOUR CODE HERE
x = x.view(-1); print(x.size())
x = x.view(3,28,28); print(x.size())


Timestamp: 20-11-26--17-15-56
torch.Size([2352])
torch.Size([3, 28, 28])


### Question 3

Consider the score vector $s=[-1.2,4.5,2.3,-0.2]$ to be the output of a 4-class classification network. Convert the score vector $s$ into a probability vector with the softmax operator. Print the probabilities. 

Implement a Python function that returns the index of the class with the highest probability. Print the index of the highest probability for the above score vector $s$. Note that the 4 classes are indexed with integer values $\{0,1,2,3\}$. 

In [7]:
%reset -f
import torch
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))

s = torch.Tensor([-1.2,4.5,2.3,-0.2]) 

# YOUR CODE HERE
prob = torch.nn.functional.softmax(s, dim=0)
print(prob)

def get_index(prob):
    return torch.argmax(prob, dim=0)

print(get_index(prob))

Timestamp: 20-11-26--17-17-51
tensor([0.0030, 0.8903, 0.0986, 0.0081])
tensor(1)


### Question 4

Implement a Python function for the activation function $$\sigma(x)=\frac{2e^{x}-e^{-x}}{2e^{x}+e^{-x}}$$

Print the activation values of the input tensor $x=[2.5,-1.2,0.0,-8.2]$ with function $\sigma$. 


In [17]:
%reset -f
import torch
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))

x = torch.Tensor([2.5,-1.2,0.0,-8.2])

# YOUR CODE HERE
def sigma(x):
    sig = (2*torch.exp(x) - torch.exp(-x))/(2*torch.exp(x) + torch.exp(-x))
    return sig
    
print(sigma(x))

Timestamp: 20-11-26--17-19-52
tensor([ 0.9933, -0.6929,  0.3333, -1.0000])


### Question 5

Implement a PyTorch class for the following layer

$$s = \sigma(W x + b)$$

with the non-linear activation function $\sigma$ defined in Question 4. 

Print the output tensor $s$ of dimension 2 given the input tensor $x=[2.3,-1.4,3.9]$.

Note that $W$ and $b$ can be any (random) tensors.

In [18]:
%reset -f
import torch
import torch.nn as nn
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))

x = torch.Tensor([2.3,-1.4,3.9])

# YOUR CODE HERE
def sigma(x):
    return (2*torch.exp(x) - torch.exp(-x))/(2*torch.exp(x) + torch.exp(-x))

class one_layer_net(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.layer1 = nn.Linear(input_size, output_size)
        
    def forward(self, x):
        x = self.layer1(x)
        x = sigma(x)
        return x
    
net = one_layer_net(3, 2)
print(net(x))

Timestamp: 20-11-26--17-22-46
tensor([0.3452, 0.8968], grad_fn=<DivBackward0>)


### Question 6

Given a minibatch $s=[ [3.6,-1.1], [-2.1,6.0] ]$ of scores of 2 data points with 2 classes. Compute the mean cross entropy value for this minibatch with the labels $[0,1]$.

In [20]:
%reset -f
import torch
import torch.nn as nn
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))

score = torch.Tensor([[3.6,-1.1], [-2.1,6.0]])
label = torch.LongTensor([0,1])

# YOUR CODE HERE
criterion = nn.CrossEntropyLoss()
loss = criterion(score, label)
print(loss.detach().item())

Timestamp: 20-11-26--17-23-53
0.004678829573094845


### Question 7

Implement a class of 3-layer MLP with the activation function of Question 4 such that

$$s = W_3\sigma(W_2\sigma(W_1 x + b_1)+b_2)+b_3)$$

Instantiate a network with 784 as input dimension, 25 as hidden dimension and 10 as output dimension. Print the network and the total number of parameters.

Use 10 epochs to train the network with batch size 100 and learning rate 0.01. Print the loss and error of the training set after 10 epochs.


In [30]:
%reset -f
import torch
import torch.nn as nn
import utils
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))
from utils import *
data_path=check_mnist_dataset_exists()
train_data=torch.load(data_path+'mnist/train_data.pt')
train_label=torch.load(data_path+'mnist/train_label.pt')

# YOUR CODE HERE
def sigma(x):
    return (2*torch.exp(x) - torch.exp(-x))/(2*torch.exp(x) + torch.exp(-x))

class three_layer_net(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2,  output_size):
        super(three_layer_net , self).__init__()
        
        self.layer1 = nn.Linear(input_size, hidden_size1, bias=True) 
        self.layer2 = nn.Linear(hidden_size1, hidden_size2, bias=True) 
        self.layer3 = nn.Linear(hidden_size2, output_size, bias=True)  
        
    def forward(self, x):
        
        y       = self.layer1(x) 
        y_hat   = sigma(y) 
        z       = self.layer2(y_hat) 
        z_hat   = sigma(z) 
        scores  = self.layer3(z_hat)
        
        return scores
    
net = three_layer_net(784, 25, 25, 10)
print(net)
print(sum(p.numel() for p in net.parameters() if p.requires_grad))
utils.display_num_param(net)

bs = 100
my_lr = 0.01
criterion = nn.CrossEntropyLoss()

import time
device = torch.device("cpu")

start = time.time()
for epoch in range(10):
    
    # reset optimizer with new learning rate
    optimizer = torch.optim.SGD(net.parameters(), lr=my_lr)
    
    running_loss = 0
    running_error = 0
    num_batches = 0
    
    shuffled_indices=torch.randperm(len(train_data)) # 60000
    
    for count in range(0, len(train_data), bs):
        # reset gradients
        optimizer.zero_grad() 
        # create minibatch
        indices = shuffled_indices[count:count+bs]
        minibatch_data = train_data[indices].to(device)   
        minibatch_label = train_label[indices].to(device) 
        
        inputs = minibatch_data.view(bs, 784) # reshape to fit network 
        # Start tracking all operations that will be done on "inputs"
        inputs.requires_grad_()
        
        scores = net(inputs)
        
        loss = criterion(scores, minibatch_label) # compute CEL
        loss.backward()  # compute gradients via backward pass
        optimizer.step() # update weights using SGD
        
        running_loss += loss.detach().item()
        error = utils.get_error(scores.detach(), minibatch_label)
        running_error += error.detach().item()
        num_batches += 1
    
    total_loss = running_loss/num_batches
    total_error = running_error/num_batches
    elapsed = time.time() - start
    
print(f"epoch={epoch+1}, time={elapsed:5f}, loss={total_loss:5f}, error={total_error*100:5f}%, lr={my_lr:5f}")

Timestamp: 20-11-26--17-31-19
three_layer_net(
  (layer1): Linear(in_features=784, out_features=25, bias=True)
  (layer2): Linear(in_features=25, out_features=25, bias=True)
  (layer3): Linear(in_features=25, out_features=10, bias=True)
)
20535
There are 20535 (0.02 million) parameters in this neural network
epoch=10, time=8.035661, loss=0.310377, error=8.738333%, lr=0.010000


### Question 8

Implement a class of 3-layer MLP with the ReLU activation function. Instantiate a network with 784 as input dimension, 7 as hidden dimension and 10 as output dimension. 

Use 20 epochs to train the network with batch size 100.

Implement the following learning rate (lr) schedule. Start with an initial lr of 0.5. Reduce the lr value at each epoch by a factor of 2.0 (that is lr/2.0) if the error on the validation set does not decrease. Print the loss and the error of the training set, and the lr after 20 epochs. 

What is the error of the training set if the initial lr is 0.5 and no learning rate schedule is used? 


In [1]:
%reset -f
import torch
import torch.nn as nn
import utils
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))
from utils import *
data_path=check_fashion_mnist_dataset_exists()
train_data=torch.load(data_path+'fashion-mnist/train_data.pt')
train_label=torch.load(data_path+'fashion-mnist/train_label.pt')
idx = torch.arange(60000)
idx_train = idx[:59000]
idx_val = idx[59000:]
val_data = train_data[idx_val]
val_label = train_label[idx_val]
train_data = train_data[idx_train]
train_label = train_label[idx_train]

print('Size of training set',train_data.size())
print('Size of validation set',val_data.size())

# YOUR CODE HERE

class three_layer_net(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2,  output_size):
        super(three_layer_net , self).__init__()
        
        self.layer1 = nn.Linear(input_size, hidden_size1, bias=True) 
        self.layer2 = nn.Linear(hidden_size1, hidden_size2, bias=True) 
        self.layer3 = nn.Linear(hidden_size2, output_size, bias=True)  
        
    def forward(self, x):
        
        y       = self.layer1(x) 
        y_hat   = torch.nn.functional.relu(y) 
        z       = self.layer2(y_hat) 
        z_hat   = torch.nn.functional.relu(z) 
        scores  = self.layer3(z_hat)
        
        return scores
    
net = three_layer_net(784, 7, 7, 10)
print(net)
print(sum(p.numel() for p in net.parameters() if p.requires_grad))
utils.display_num_param(net)

import time
device = torch.device("cpu")

def eval_on_test_set(bs):
    running_error = 0
    num_batches = 0
    for i in range(0, len(val_data), bs):
        minibatch_data = val_data[i:i+bs].to(device)
        minibatch_label = val_label[i:i+bs].to(device)
        inputs = minibatch_data.view(bs, 784)
        scores = net(inputs)
        error = utils.get_error(scores, minibatch_label)
        running_error += error.detach().item()
        num_batches += 1
    total_error = running_error / num_batches
    print(f"=> test error: {total_error*100:5f} %")
    return total_error

from IPython.core.debugger import set_trace
def trainer(lr_schedule=True):    
    bs = 100
    my_lr = 0.5
    criterion = nn.CrossEntropyLoss()
    prev_val = None
    start = time.time()
    for epoch in range(20):

        # reset optimizer with new learning rate
        optimizer = torch.optim.SGD(net.parameters(), lr=my_lr)

        running_loss = 0
        running_error = 0
        num_batches = 0
    
        shuffled_indices=torch.randperm(len(train_data)) # 60000

        for count in range(0, len(train_data), bs):
            # reset gradients
            optimizer.zero_grad() 
            # create minibatch
            indices = shuffled_indices[count:count+bs]
            minibatch_data = train_data[indices].to(device)   
            minibatch_label = train_label[indices].to(device) 

            inputs = minibatch_data.view(bs, 784) # reshape to fit network 
            # Start tracking all operations that will be done on "inputs"
            inputs.requires_grad_()

            scores = net(inputs)

            loss = criterion(scores, minibatch_label) # compute CEL
            loss.backward()  # compute gradients via backward pass
            optimizer.step() # update weights using SGD

            running_loss += loss.detach().item()
            error = utils.get_error(scores.detach(), minibatch_label)
            running_error += error.detach().item()
            num_batches += 1

        total_loss = running_loss/num_batches
        total_error = running_error/num_batches
        elapsed = time.time() - start
        print(f"epoch={epoch+1}, time={elapsed:5f}, loss={total_loss:5f}, error={total_error*100:5f}%, lr={my_lr:5f}")
        val_error = eval_on_test_set(bs)
        
        #set_trace()
        if lr_schedule and prev_val and val_error >= prev_val:
            print("reducing")
            my_lr = my_lr/2.0
        prev_val = val_error
        
    print(f"epoch={epoch+1}, time={elapsed:5f}, loss={total_loss:5f}, error={total_error*100:5f}%, val_error={val_error*100:5f}%, lr={my_lr:5f}")     

print(f"With LR Scheduler: ")
trainer(True)
net = three_layer_net(784, 7, 7, 10)
print("")
print(f"Without LR Scheduler: ")
trainer(False)

Timestamp: 20-11-26--17-46-29
Size of training set torch.Size([59000, 28, 28])
Size of validation set torch.Size([1000, 28, 28])
three_layer_net(
  (layer1): Linear(in_features=784, out_features=7, bias=True)
  (layer2): Linear(in_features=7, out_features=7, bias=True)
  (layer3): Linear(in_features=7, out_features=10, bias=True)
)
5631
There are 5631 (0.01 million) parameters in this neural network
With LR Scheduler: 
epoch=1, time=0.566378, loss=1.198555, error=50.322034%, lr=0.500000
=> test error: 41.600001 %
epoch=2, time=1.049273, loss=0.925965, error=38.688136%, lr=0.500000
=> test error: 30.200000 %
epoch=3, time=1.525797, loss=0.773893, error=30.515254%, lr=0.500000
=> test error: 27.300000 %
epoch=4, time=2.030067, loss=0.706061, error=26.961017%, lr=0.500000
=> test error: 22.400000 %
epoch=5, time=2.530285, loss=0.651028, error=24.240678%, lr=0.500000
=> test error: 22.100000 %
epoch=6, time=3.051214, loss=0.630401, error=22.913560%, lr=0.500000
=> test error: 21.400000 %
e

### Question 9

Implement a class of 3-layer MLP with the ReLU activation function. Instantiate a network with 784 as input dimension, 25 as hidden dimension and 1 as output dimension. 

The output dimension is 1 because the problem is changed from a classification task to a regression task. The regression task consists in predicting the class index, here the values 0,1,2,3,...,9 for the ten classes of FASHION-MNIST.

Implement the standard regression loss

$$ L = \frac{1}{n}\sqrt{\sum_{i=1}^n (s_i - \textrm{cl}(i))^2}$$

where $s_i=\textrm{3-layer MLP}(x_i)$ is the output of the 3-layer MLP and $\textrm{cl}(i)$ is the class index of data point $x_i$.

Use 10 epochs to train the network with batch size 100 and learning rate 0.001. Print the loss of the training set.


In [5]:
%reset -f
import torch
import torch.nn as nn
import utils
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))
from utils import *
data_path=check_fashion_mnist_dataset_exists()
train_data=torch.load(data_path+'fashion-mnist/train_data.pt')
train_label=torch.load(data_path+'fashion-mnist/train_label.pt')

# YOUR CODE HERE
class three_layer_net(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2,  output_size):
        super(three_layer_net , self).__init__()
        
        self.layer1 = nn.Linear(input_size, hidden_size1, bias=True) 
        self.layer2 = nn.Linear(hidden_size1, hidden_size2, bias=True) 
        self.layer3 = nn.Linear(hidden_size2, output_size, bias=True)  
        
    def forward(self, x):
        
        y       = self.layer1(x) 
        y_hat   = torch.nn.functional.relu(y) 
        z       = self.layer2(y_hat) 
        z_hat   = torch.nn.functional.relu(z) 
        scores  = self.layer3(z_hat)
        
        return scores
    
net = three_layer_net(784, 25, 25, 1)
print(net)
utils.display_num_param(net)

bs = 100
my_lr = 0.001 

def regression_loss(scores, labels, bs):
    return ( ( scores.squeeze() - minibatch_label.float() )**2 ).sum().sqrt()/ bs

import time
device = torch.device("cpu")

start = time.time()
for epoch in range(10):
    
    # reset optimizer with new learning rate
    optimizer = torch.optim.SGD(net.parameters(), lr=my_lr)
    
    running_loss = 0
    running_error = 0
    num_batches = 0
    
    shuffled_indices=torch.randperm(len(train_data)) # 60000
    
    for count in range(0, len(train_data), bs):
        # reset gradients
        optimizer.zero_grad() 
        # create minibatch
        indices = shuffled_indices[count:count+bs]
        minibatch_data = train_data[indices].to(device)   
        minibatch_label = train_label[indices].to(device) 
        
        inputs = minibatch_data.view(bs, 784) # reshape to fit network 
        # Start tracking all operations that will be done on "inputs"
        inputs.requires_grad_()
        
        scores = net(inputs)
        
        loss = regression_loss(scores, minibatch_label, bs) # compute CEL
        loss.backward()  # compute gradients via backward pass
        optimizer.step() # update weights using SGD
        
        running_loss += loss.detach().item()
        num_batches += 1
    
    total_loss = running_loss/num_batches
    elapsed = time.time() - start
    
print(f"epoch={epoch+1}, time={elapsed:5f}, loss={total_loss:5f}, lr={my_lr:5f}")

Timestamp: 20-11-26--17-54-51
three_layer_net(
  (layer1): Linear(in_features=784, out_features=25, bias=True)
  (layer2): Linear(in_features=25, out_features=25, bias=True)
  (layer3): Linear(in_features=25, out_features=1, bias=True)
)
There are 20301 (0.02 million) parameters in this neural network
epoch=10, time=5.451626, loss=0.224843, lr=0.001000


### Question 10

Implement a class of 1-layer MLP, that is $$s=Wx+b$$ 

with no activation function. Instantiate a network with 784 as input dimension and 2 as output dimension. 

The output dimension is 2 because the task is to classify digits 1s and 7s with 6,000 training data for the class 1 and 600 training data for the class of 7. This classification task is unbalanced. 

To correct the unbalanced training set, a weighted cross entropy loss is used and defined as

$$ L = -\frac{1}{N}\sum_{i=1}^N w^{(i)}. \log \Big(\textrm{entry cl($i$) of probability vector } p^{(i)} \Big)$$

where $cl($i$)$ is the class index of the $i^{th}$ training data, $p^{(i)}$ is the probability vector computed by the network, and $w^{(i)}$ is equal to $0.1$ for data belonging to the class of 1s and $w^{(i)}$ equal to $1.0$ for data belonging to the class of 7s.

Implement the weighted cross entropy loss. Use 20 epochs to train the network with batch size 100 and learning rate 0.01. Print the weighted cross entropy loss and error value for the training set. Print the error value for the test set.

Compute and compare theses values with the standard non-weighted cross entropy loss defined as

$$ L = -\frac{1}{N}\sum_{i=1}^N \log \Big(\textrm{entry cl($i$) of probability vector } p^{(i)} \Big)$$



In [6]:
%reset -f
from packaging import version
import torch
import torch.nn as nn
import utils
import datetime
print('Timestamp:',datetime.datetime.now().strftime("%y-%m-%d--%H-%M-%S"))
from utils import *
data_path=check_fashion_mnist_dataset_exists()
train_data=torch.load(data_path+'fashion-mnist/train_data.pt')
train_label=torch.load(data_path+'fashion-mnist/train_label.pt')
test_data=torch.load(data_path+'fashion-mnist/test_data.pt')
test_label=torch.load(data_path+'fashion-mnist/test_label.pt')

if version.parse(torch.__version__) < version.parse("1.6.0"):
    idx_class0 = (train_label==1-1).nonzero().squeeze()
    idx_class1 = (train_label==7-1).nonzero().squeeze()
else:
    idx_class0 = (train_label==1-1).nonzero(as_tuple=False).squeeze()
    idx_class1 = (train_label==7-1).nonzero(as_tuple=False).squeeze()
idx_class0 = idx_class0[:6000]
idx_class1 = idx_class1[:600]
train_data = train_data[torch.cat((idx_class0,idx_class1))]
train_label = train_label[torch.cat((idx_class0,idx_class1))]
train_label[train_label==1-1] = 0 # class 1 has label 0
train_label[train_label==7-1] = 1 # class 7 has label 1

if version.parse(torch.__version__) < version.parse("1.6.0"):
    idx_class0 = (test_label==1-1).nonzero().squeeze()
    idx_class1 = (test_label==7-1).nonzero().squeeze()
else:
    idx_class0 = (test_label==1-1).nonzero(as_tuple=False).squeeze()
    idx_class1 = (test_label==7-1).nonzero(as_tuple=False).squeeze() 
idx_class0 = idx_class0[:6000]
idx_class1 = idx_class1[:600]
test_data = test_data[torch.cat((idx_class0,idx_class1))]
test_label = test_label[torch.cat((idx_class0,idx_class1))]
test_label[test_label==1-1] = 0 # class 1 has label 0
test_label[test_label==7-1] = 1 # class 7 has label 1
test_data = test_data[:200]
test_label = test_label[:200]

print('Size of training set:',train_data.size())
print('Size of test set:',test_data.size())


# YOUR CODE HERE
class one_layer_MLP(nn.Module):
    def __init__(self, input_size, output_size):
        super(one_layer_MLP , self).__init__()
        self.layer = nn.Linear(  input_size, output_size )
    def forward(self, x):
        score = self.layer(x)
        return score

net = one_layer_MLP(784,2)
bs = 100
optimizer=torch.optim.SGD( net.parameters() , lr=0.01 )

for epoch in range(20):
    running_loss=0
    running_error=0
    num_batches=0
    shuffled_indices=torch.randperm(train_data.size(0))            
    for count in range(0,train_data.size(0),bs):
        optimizer.zero_grad()
        indices = shuffled_indices[count:count+bs]
        minibatch_data = train_data[indices]
        minibatch_label = train_label[indices]
        inputs = minibatch_data.view(bs,784)
        inputs.requires_grad_()
        scores = net( inputs ) 
        
        # weighted cross entropy
        p = torch.softmax(scores, dim=1)
        log_prob = -torch.log(p)
        w = torch.zeros(bs)
        w[minibatch_label==0] = 1
        w[minibatch_label==1] = 1/10
        loss = (w* log_prob[torch.arange(bs),minibatch_label]).mean() # weighted cross entropy
        #loss = log_prob[torch.arange(bs),minibatch_label].mean() # un-weighted cross entropy
        error = get_error( scores.detach() , minibatch_label)
        running_error += error.item()

        loss.backward()
        optimizer.step()
        running_loss += loss.detach().item()
        num_batches+=1
    total_loss = running_loss/num_batches
    total_error = running_error/num_batches
    
    # test error
    scores = net( test_data.view(200,784) ) 
    test_error = get_error( scores.detach() , test_label).item()
           
    print('epoch=',epoch, ' loss=', total_loss, ' train_error=', 100*total_error, ' test_error=', 100*test_error)



Timestamp: 20-11-26--17-56-35
Size of training set: torch.Size([6600, 28, 28])
Size of test set: torch.Size([200, 28, 28])
epoch= 0  loss= 0.08878127254094138  train_error= 9.924242261684302  test_error= 0.0
epoch= 1  loss= 0.06297045353461396  train_error= 9.090909000599023  test_error= 0.0
epoch= 2  loss= 0.06116464361548424  train_error= 9.090908819978887  test_error= 0.0
epoch= 3  loss= 0.05978196108657302  train_error= 9.090909000599023  test_error= 0.0
epoch= 4  loss= 0.058504496842171204  train_error= 9.090908910288956  test_error= 0.0
epoch= 5  loss= 0.057303987528112804  train_error= 9.090908910288956  test_error= 0.0
epoch= 6  loss= 0.056168906108448  train_error= 9.090909090909092  test_error= 0.0
epoch= 7  loss= 0.05512016540336789  train_error= 9.090908910288956  test_error= 0.0
epoch= 8  loss= 0.05413526025685397  train_error= 9.106060681921063  test_error= 0.0
epoch= 9  loss= 0.05321478778778604  train_error= 9.106060681921063  test_error= 0.0
epoch= 10  loss= 0.05236453