# AI6103 DL Quiz Preparation

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from random import randint
import utils
import time
from torchsummary import summary
from IPython.display import Math
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

## L01 - Introduction

Amount of data $n$ required to achieve super human performance: <br> 
$\Large n = \frac{\mathit{features}}{error} = \frac{d}{e}$

In [2]:
d = 1000*1000
e = 1
n = d//e; print(n)

1000000


## L02 - Linear Algebra

### Vectors

In [3]:
# Vector addition
v1 = torch.LongTensor([1,1,2]); print(v1)
v2 = torch.LongTensor([5,-1,2]); print(v1)
vpv = v1 + v2 ;print(vpv)

tensor([1, 1, 2])
tensor([1, 1, 2])
tensor([6, 0, 4])


In [4]:
# Vector multiplication
c = 2 
v1 = torch.LongTensor([1,1,2]); print(v1)
cv = c*v1; print(cv)

tensor([1, 1, 2])
tensor([2, 2, 4])


In [5]:
## Inner product
v1 = torch.LongTensor([1,1,2]); print(v1)
v2 = torch.LongTensor([1,2,3]); print(v1)
v1v2 = torch.matmul(v1, v2); print(v1v2)

tensor([1, 1, 2])
tensor([1, 1, 2])
tensor(9)


### Matrices

In [6]:
M1 = torch.LongTensor([[1,2], [3,4],[5,0]]); print(M1)
M2 = torch.LongTensor([[10,10], [20,20],[30,30]]); print(M2)
M1pM2 = M1+M2; print(M1pM2)

tensor([[1, 2],
        [3, 4],
        [5, 0]])
tensor([[10, 10],
        [20, 20],
        [30, 30]])
tensor([[11, 12],
        [23, 24],
        [35, 30]])


In [7]:
c = 2
M1 = torch.LongTensor([[1,2], [3,4],[5,0]]); print(M1)
cM1 = c* M1; print(cM1)

tensor([[1, 2],
        [3, 4],
        [5, 0]])
tensor([[ 2,  4],
        [ 6,  8],
        [10,  0]])


### Matrix-Vector

In [8]:
W = torch.LongTensor([[1,2,3],[4,5,6]]); print(f"W: {W.shape}")
x = torch.LongTensor([1,-2,2]); print(f"x: {x.shape}")
b = torch.LongTensor([7, 10]); print(f"b: {b.shape}")
z = torch.matmul(W,x)+b
print(f"z: {z} {z.shape}")

W: torch.Size([2, 3])
x: torch.Size([3])
b: torch.Size([2])
z: tensor([10, 16]) torch.Size([2])


In [9]:
## Inner product
A = torch.LongTensor([[1,1,1],[2,3,0]])
B = torch.LongTensor([[1,2,1,1],[2,0,1,1],[3,2,1,1]])
C = torch.mm(A,B)
print(C)

tensor([[6, 4, 3, 3],
        [8, 4, 5, 5]])


### Inner & Outer Product

In [10]:
# Outer product
x = torch.LongTensor([1,2,3]); print(x) #3x1
x1 = x.unsqueeze(1); print(x)
y = torch.LongTensor([0,1,2]); print(y) #1x3

outerpdt = x1 * y; print(outerpdt) #3x3
outerpdt2 = torch.ger(x,y); print(outerpdt2)

tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([0, 1, 2])
tensor([[0, 1, 2],
        [0, 2, 4],
        [0, 3, 6]])
tensor([[0, 1, 2],
        [0, 2, 4],
        [0, 3, 6]])


## L03 - Vanilla NN (Part 1)

In [11]:
## Softmax
B = torch.Tensor([[1,2,3,4],
                 [1,2,5,3]])
print(B, B.size()) # 2,4
prob = F.softmax(B, dim=1) #rows (2) matrices
print(f"=> Softmax over dim 1 (rows)")
print(prob)
print(prob.sum(1)) 
print("")
prob = F.softmax(B, dim=0) #cols (4) vectors
print(f"=> Softmax over dim 0 (cols)")
print(prob)
print(torch.max(prob))
print(prob.sum(0)) 

tensor([[1., 2., 3., 4.],
        [1., 2., 5., 3.]]) torch.Size([2, 4])
=> Softmax over dim 1 (rows)
tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0152, 0.0414, 0.8310, 0.1125]])
tensor([1., 1.])

=> Softmax over dim 0 (cols)
tensor([[0.5000, 0.5000, 0.1192, 0.7311],
        [0.5000, 0.5000, 0.8808, 0.2689]])
tensor(0.8808)
tensor([1., 1., 1., 1.])


In [6]:
p_target = torch.Tensor([0,0,1,0])
probs = torch.Tensor([0.3,0.2,0.2,0.25])
err = p_target - probs; print(err, err.shape)

tensor([-0.3000, -0.2000,  0.8000, -0.2500]) torch.Size([4])


In [7]:
x = torch.rand((32)); print(x)
# ex = err.unsqueeze(1) * x; print(ex, ex.shape)
ex2 = torch.ger(err,x); print(ex2, ex2.shape) #torch.ger == torch.outer

tensor([0.1894, 0.4080, 0.5163, 0.7744, 0.3590, 0.5222, 0.6499, 0.6188, 0.7693,
        0.6438, 0.4193, 0.2937, 0.0959, 0.9059, 0.3426, 0.1874, 0.9540, 0.6324,
        0.1819, 0.2522, 0.7047, 0.5260, 0.1480, 0.3789, 0.1883, 0.5540, 0.8351,
        0.5052, 0.9620, 0.8050, 0.4492, 0.1944])
tensor([[-0.0568, -0.1224, -0.1549, -0.2323, -0.1077, -0.1566, -0.1950, -0.1856,
         -0.2308, -0.1931, -0.1258, -0.0881, -0.0288, -0.2718, -0.1028, -0.0562,
         -0.2862, -0.1897, -0.0546, -0.0757, -0.2114, -0.1578, -0.0444, -0.1137,
         -0.0565, -0.1662, -0.2505, -0.1515, -0.2886, -0.2415, -0.1348, -0.0583],
        [-0.0379, -0.0816, -0.1033, -0.1549, -0.0718, -0.1044, -0.1300, -0.1238,
         -0.1539, -0.1288, -0.0839, -0.0587, -0.0192, -0.1812, -0.0685, -0.0375,
         -0.1908, -0.1265, -0.0364, -0.0504, -0.1409, -0.1052, -0.0296, -0.0758,
         -0.0377, -0.1108, -0.1670, -0.1010, -0.1924, -0.1610, -0.0898, -0.0389],
        [ 0.1515,  0.3264,  0.4131,  0.6195,  0.2872,  0.4177

## L04 - Vanilla NN

In [14]:
from prettytable import PrettyTable
def count_parameters(model):
    table = PrettyTable(["Modules", "Parameters"])
    total_params = 0
    for name, parameter in model.named_parameters():
        if not parameter.requires_grad: 
            continue
        param = parameter.numel()
        table.add_row([name, param])
        total_params+=param
    print(table)
    print(f"Total Trainable Params: {total_params}")
    return total_params

In [15]:
class One_Layer_Net(nn.Module):
    def __init__(self, input_size, output_size):
        super(One_Layer_Net, self).__init__()
        self.linear_layer = nn.Linear(input_size,output_size,bias=True)
    def forward(self, x): 
#         x = self.linear_layer(x)
#         p = F.softmax(x, dim=1)
        return p
    
net = One_Layer_Net(784, 10)


count_parameters(net)

+---------------------+------------+
|       Modules       | Parameters |
+---------------------+------------+
| linear_layer.weight |    7840    |
|  linear_layer.bias  |     10     |
+---------------------+------------+
Total Trainable Params: 7850


7850

In [16]:
class LeNet5_convnet(nn.Module):

    def __init__(self):
        super(LeNet5_convnet, self).__init__()
        # CL1:   28 x 28  -->    50 x 28 x 28 
        self.conv1 = nn.Conv2d(1,   50,  kernel_size=3,  padding=1 )
        # MP1: 50 x 28 x 28 -->    50 x 14 x 14
        self.pool1  = nn.MaxPool2d(2,2)
        # CL2:   50 x 14 x 14  -->    100 x 14 x 14 
        self.conv2 = nn.Conv2d(50, 100,  kernel_size=3,  padding=1 ) # COMPLETE HERE
        # MP2: 100 x 14 x 14 -->    100 x 7 x 7
        self.pool2 = nn.MaxPool2d(2,2) # COMPLETE HERE
        # LL1:   100 x 7 x 7 = 4900 -->  100 
        self.linear1 = nn.Linear(4900, 100) # COMPLETE HERE
        # LL2:   100  -->  10 
        self.linear2 = nn.Linear(100, 10) # COMPLETE HERE


    def forward(self, x):
#         # CL1:   28 x 28  -->    50 x 28 x 28 
#         x = self.conv1(x)
#         x = F.relu(x)
#         # MP1: 50 x 28 x 28 -->    50 x 14 x 14
#         x = self.pool1(x)
#         # CL2:   50 x 14 x 14  -->    100 x 14 x 14
#         x = self.conv2(x) # COMPLETE HERE
#         x = F.relu(x) # COMPLETE HERE
#         # MP2: 100 x 14 x 14 -->    100 x 7 x 7
#         x = self.pool2(x) # COMPLETE HERE
#         # LL1:   100 x 7 x 7 = 4900  -->  100 
#         x = x.view(-1, 4900)
#         x = self.linear1(x) # COMPLETE HERE
#         x = F.relu(x)# COMPLETE HERE
#         # LL2:   4900  -->  10 
#         x = self.linear2(x) # COMPLETE HERE
        return x
    
conv = LeNet5_convnet()
count_parameters(conv)

+----------------+------------+
|    Modules     | Parameters |
+----------------+------------+
|  conv1.weight  |    450     |
|   conv1.bias   |     50     |
|  conv2.weight  |   45000    |
|   conv2.bias   |    100     |
| linear1.weight |   490000   |
|  linear1.bias  |    100     |
| linear2.weight |    1000    |
|  linear2.bias  |     10     |
+----------------+------------+
Total Trainable Params: 536710


536710

In [ ]:
class LeNet5_convnet(nn.Module):

    def __init__(self):
        super(LeNet5_convnet, self).__init__()
        # CL1:   28 x 28  -->    50 x 28 x 28 
        self.conv1 = nn.Conv2d(1,   50,  kernel_size=3,  padding=1 )
        # MP1: 50 x 28 x 28 -->    50 x 14 x 14
        self.pool1  = nn.MaxPool2d(2,2)
        # CL2:   50 x 14 x 14  -->    100 x 14 x 14 
        self.conv2 = nn.Conv2d(50, 100,  kernel_size=3,  padding=1 ) # COMPLETE HERE
        # MP2: 100 x 14 x 14 -->    100 x 7 x 7
        self.pool2 = nn.MaxPool2d(2,2) # COMPLETE HERE
        # LL1:   100 x 7 x 7 = 4900 -->  100 
        self.linear1 = nn.Linear(4900, 100) # COMPLETE HERE
        # LL2:   100  -->  10 
        self.linear2 = nn.Linear(100, 10) # COMPLETE HERE


    def forward(self, x):

In [40]:
def cal_conv_filter(I: int, O: int, P:int = 0, S:int=1):
    assert S > 0
    f = I + 2*P - S*(O-1)
    print(f"CONV filter size for I:{I} O:{O}, padding:{P} stride:{S} = {f}")
    return f

In [41]:
cal_conv_filter(32, 28, 0, 1)
cal_conv_filter(14, 10, 0, 1)

CONV filter size for I:32 O:28, padding:0 stride:1 = 5
CONV filter size for I:14 O:10, padding:0 stride:1 = 5


5

In [45]:
cal_conv_filter(128, 42, 0, 3)

CONV filter size for I:128 O:42, padding:0 stride:3 = 5


5

In [42]:
def cal_max_pool(I: int, O: int):
    # P == 0, S == f
    f = I//O
    print(f"MP filter size for I:{I} O:{O} = {f}")
    return f

In [39]:
cal_max_pool(28, 14)

MP filter size for I:28 O:14 = 2


2