# Lab 01: Introduction to PyTorch  

In [1]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [2]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [3]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [4]:
A=torch.rand(10,2)
print(A)

tensor([[0.3032, 0.5273],
        [0.9611, 0.7025],
        [0.1427, 0.5284],
        [0.1563, 0.1021],
        [0.2276, 0.4817],
        [0.0279, 0.0471],
        [0.9853, 0.6469],
        [0.0055, 0.2400],
        [0.0842, 0.2788],
        [0.9653, 0.0575]])


### Construct a 10 x 2 matrix filled with zeros

In [5]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [6]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.1897, 0.4951],
         [0.6689, 0.4158]],

        [[0.9123, 0.3509],
         [0.7718, 0.5518]],

        [[0.9902, 0.5857],
         [0.7570, 0.9430]],

        [[0.0596, 0.4405],
         [0.8158, 0.7101]],

        [[0.6702, 0.0207],
         [0.5237, 0.6211]]])


In [7]:
B.size()

torch.Size([5, 2, 2])

In [8]:
B.dim()

3

In [9]:
B.type()

'torch.FloatTensor'

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [10]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.5267, 0.3884],
         [0.9814, 0.8410]],

        [[0.9071, 0.5976],
         [0.8369, 0.9639]],

        [[0.8912, 0.2643],
         [0.6002, 0.9248]]])


In [11]:
print(  A.dim()   )

3


In [12]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [13]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [14]:
B=torch.rand(3,5)
print(B)

tensor([[0.2285, 0.3059, 0.8160, 0.7996, 0.9933],
        [0.5550, 0.7225, 0.9296, 0.0796, 0.8340],
        [0.0335, 0.9682, 0.0047, 0.4607, 0.1639]])


In [15]:
print( B.dim()  )

2


In [16]:
print( B.size()  )

torch.Size([3, 5])


In [17]:
print( B.size(0) )

3


In [18]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [19]:
x=torch.rand(7)
print(x)

tensor([0.1996, 0.1007, 0.2025, 0.4443, 0.7526, 0.9292, 0.8750])


In [20]:
print( x.dim() )

1


In [21]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [22]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.7964, 0.6157],
        [0.8750, 0.5638]])

tensor([[0.0329, 0.3790],
        [0.5487, 0.1869]])

tensor([[0.0657, 0.7581],
        [1.0974, 0.3739]])

tensor([[0.0657, 0.7581],
        [1.0974, 0.3739]])

tensor([[0.0262, 0.2334],
        [0.4801, 0.1054]])


### Floats versus integers

In [23]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [24]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [25]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [26]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [27]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [31]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([9, 2, 1, 0, 6, 8, 3, 7, 4, 5])
torch.LongTensor


In [32]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [33]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [34]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [35]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [36]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [37]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [38]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [39]:
print( y[0] )

tensor([0, 1])


In [40]:
print( y[1] )

tensor([2, 3])


In [41]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [42]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [43]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [44]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [45]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [46]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [47]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [48]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [49]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [50]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [51]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [52]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>
