# Lab 01 : Convolutional layer - demo

In [1]:
import torch
import torch.nn as nn

### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps 
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [2]:
mod = nn.Conv2d( 2 , 5 ,  kernel_size=3,  padding=1 )

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [3]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

print(x.size())

tensor([[[[0.1547, 0.7232, 0.6395, 0.5490, 0.7109, 0.4869],
          [0.4964, 0.5220, 0.1526, 0.6450, 0.9332, 0.9990],
          [0.5541, 0.4980, 0.8310, 0.1912, 0.4766, 0.9040],
          [0.2206, 0.8510, 0.5701, 0.0375, 0.3505, 0.2003],
          [0.4629, 0.4703, 0.2831, 0.4072, 0.9618, 0.0384],
          [0.4350, 0.4967, 0.9412, 0.7495, 0.0094, 0.4609]],

         [[0.8039, 0.9302, 0.7381, 0.5219, 0.1925, 0.9237],
          [0.5447, 0.4008, 0.4000, 0.5659, 0.2255, 0.1632],
          [0.3571, 0.1388, 0.5516, 0.6121, 0.1035, 0.9965],
          [0.5659, 0.7911, 0.2385, 0.9609, 0.2500, 0.9127],
          [0.0458, 0.7271, 0.8613, 0.8330, 0.9604, 0.3535],
          [0.9272, 0.1359, 0.2476, 0.2435, 0.5452, 0.2271]]]])
torch.Size([1, 2, 6, 6])


### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [4]:
y=mod(x)

print(y)

print(y.size())

tensor([[[[-4.3936e-01, -4.3251e-01, -3.3035e-01, -3.6198e-01, -1.6227e-01,
           -4.9804e-01],
          [-1.0225e-01,  1.0078e-01, -3.8880e-01, -9.5737e-02, -2.8944e-01,
           -2.4081e-01],
          [-4.5096e-02, -3.7237e-01, -4.8169e-01, -1.9167e-01, -3.3863e-01,
           -2.9129e-01],
          [-2.4978e-01, -2.9351e-01, -2.8328e-01, -6.7976e-01, -3.2800e-01,
           -2.7658e-01],
          [-1.3160e-02, -5.7918e-02, -3.1476e-01, -4.3242e-01,  6.2473e-02,
           -4.4910e-01],
          [-2.1668e-01, -1.1719e-01, -3.9752e-02,  7.7661e-02, -1.7342e-01,
           -1.1002e-01]],

         [[-3.8525e-01, -5.8206e-01, -4.2810e-01, -3.9528e-01, -4.3835e-01,
           -3.2070e-01],
          [-4.6603e-01, -4.7566e-01, -6.3022e-01, -5.2220e-01, -5.3812e-01,
           -3.0897e-01],
          [-1.2078e-01, -6.1115e-01, -5.0295e-01, -5.0360e-01, -8.7602e-01,
           -3.9994e-01],
          [-4.5242e-01, -4.0612e-01, -6.7816e-01, -4.6114e-01, -8.8006e-01,
           -5

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [5]:
print(mod.weight)

print(mod.weight.size())

Parameter containing:
tensor([[[[-0.1534,  0.1850,  0.0978],
          [-0.1809,  0.2348, -0.1412],
          [ 0.1115, -0.1740,  0.2325]],

         [[ 0.0765,  0.1219, -0.0364],
          [ 0.0858, -0.1842,  0.0661],
          [-0.2204, -0.0799, -0.2018]]],


        [[[-0.0967, -0.0970, -0.0841],
          [-0.1011,  0.1072, -0.1323],
          [ 0.1198, -0.0672,  0.1519]],

         [[ 0.0293, -0.0385, -0.1278],
          [-0.1823, -0.1214, -0.2138],
          [-0.2269,  0.0714,  0.1606]]],


        [[[ 0.0225, -0.1798, -0.0949],
          [ 0.1458,  0.1238,  0.0611],
          [-0.0238, -0.1559, -0.0787]],

         [[ 0.2260,  0.1684, -0.1894],
          [ 0.0525, -0.0090,  0.0745],
          [-0.1152, -0.1227,  0.0671]]],


        [[[-0.1203,  0.0469, -0.0565],
          [ 0.2083,  0.0224, -0.1875],
          [ 0.0605, -0.0856,  0.2080]],

         [[ 0.2119, -0.1842,  0.0861],
          [-0.1352, -0.1210,  0.1675],
          [ 0.1587,  0.0913, -0.1896]]],


        [[[-0.0906